apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-app-deployment
  namespace: reddit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-app
  template:
    metadata:
      labels:
        app: reddit-clone-app
    spec:  # <- This was misaligned before
      containers:
      - name: reddit-clone-app
        image: devil678/a-reddit-clone:latest
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "500m"
        ports:
        - containerPort: 3000
