kind: HorizontalPodAutoscaler
apiVersion: v1
metadata:
  name: reddit-hpa
  namespace: reddit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: reddit-clone-app-deployment
    namespace: redit
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  
