apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reddit-hpa
  namespace: reddit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reddit-clone-app-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
